name: Send RC notification

on:
  workflow_call:
    inputs:
      host_name:
        required: true
        type: string
    secrets:
      rc_webhook: 
        required: true

jobs:
  set_versions:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ inputs.host_name }}
      cancel-in-progress: true
    environment: ${{ inputs.host_name }}
    steps:
      - name: Test with failure or succeed
        run: echoo "This does not exist"
      - name: Get the result of the if condition
        if: always() 
        run: echo " ${{contains(inputs.host_name, 'infra') }}"
      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        # works for ref
        if: always() && (contains(inputs.host_name, 'ref')) || (contains(inputs.host_name, 'prod'))
        with:
          type: ${{ job.status }}
          job_name: 'Rollout of ${{ inputs.host_name }} triggered by ${{ github.actor }}:'
          url: ${{ secrets.rc_webhook }}
          channel: '#aimee-test'
          username: Autodeployment Info
