name: Send RC notification

on:
  workflow_call:
    inputs:
      host_name:
        required: true
        type: string
    secrets:
      rc_webhook: 
        required: true

jobs:
  set_versions:
  environment: approve_ref
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ inputs.host_name }}
      cancel-in-progress: true
    environment: ${{ inputs.host_name }}
    steps:
      - name: Test with failure or succeed
        run: echo "This does not exist"
      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Rollout of ${{ inputs.host_name }} triggered by ${{ github.actor }}:'
          url: ${{ secrets.rc_webhook }}
          channel: '#releases2'
          username: Autodeployment Info
